version: "3.2"  # optional since v1.27.0
services:
  system:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
  db:
    container_name: 'database-mysql'
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - '3308:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo